# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\"E\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x12\n\nbooking_id\x18\x03 \x01(\t\"H\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\"&\n\x0cPayedRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\" \n\rPayedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xad\x01\n\x0ePaymentService\x12S\n\x0eProcessPayment\x12\x1f.payment_service.PaymentRequest\x1a .payment_service.PaymentResponse\x12\x46\n\x05Payed\x12\x1d.payment_service.PayedRequest\x1a\x1e.payment_service.PayedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PAYMENTREQUEST']._serialized_start=42
  _globals['_PAYMENTREQUEST']._serialized_end=111
  _globals['_PAYMENTRESPONSE']._serialized_start=113
  _globals['_PAYMENTRESPONSE']._serialized_end=185
  _globals['_PAYEDREQUEST']._serialized_start=187
  _globals['_PAYEDREQUEST']._serialized_end=225
  _globals['_PAYEDRESPONSE']._serialized_start=227
  _globals['_PAYEDRESPONSE']._serialized_end=259
  _globals['_PAYMENTSERVICE']._serialized_start=262
  _globals['_PAYMENTSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
